name: 'yelp'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:

  yelp:

    base:
      schema: STAGING
      +materialized: view
    
    dwh:
      schema: DWH
      +materialized: table
    
    reporting:
      schema: REPORTING
      +materialized: view
        
quoting:
  database: false
  schema: false
  identifier: false

vars:
  security_database: 'SECURITY'
  security_schema: 'SEC'

on-run-start:
    - '{{unapply_row_access_policies()}}'

on-run-end:
    - '{{create_row_access_policies()}}'
    - '{{apply_row_access_policies()}}'
    - '{{create_rap_mapping_table()}}'