version: 2

sources:
  - name: YELP
    database: RAW
    tables:
      - name: YELP_ACADEMIC_DATASET_BUSINESS
      - name: YELP_ACADEMIC_DATASET_TIP
      - name: YELP_ACADEMIC_DATASET_USER

  - name: FIVETRAN
    database: RAW
    tables:
      - name: ACCOUNT